---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-bouncer
  namespace: ephemeral-roles
  annotations:
    sidecar.jaegertracing.io/inject: "true"
  labels:
    app: pod-bouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-bouncer
  template:
    metadata:
      labels:
        app: pod-bouncer
        version: "{COMMIT}"
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: pod-bouncer
      containers:
        - name: pod-bouncer
          image: ewohltman/pod-bouncer:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "50m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "256Mi"
          ports:
            - name: http
              containerPort: 8080
