---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-bouncer
  namespace: ephemeral-roles
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-bouncer
subjects:
  - kind: ServiceAccount
    name: pod-bouncer
    namespace: ephemeral-roles
